### PR TITLE
Meetup 11

### PR DESCRIPTION
**Pull request by simison**
Hey! I arranged meetup before I knew about vilniusjs.lt — somebody pointed this out so thought better do it this way! Hope this suits you.

### CODE REVIEW

**Comment by simison** [comment]
See http://www.meetup.com/Vilnius-js/events/206877582/ for original.

**Comment by simison** [comment]
Ahoy?

Sorry for pushing, but this is pretty soon. @edvinasbartkus @mmozuras

Thanks!

**Comment by mmozuras** [comment]
@simison hi, sorry for taking a while.

:+1:

**Comment by edvinasbartkus** [comment]
:+1:

**Comment by simison** [comment]
Cuuul, aciu. :-)

**Pull request merged**
